BugTracker/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.Models;
using Microsoft.AspNetCore.Mvc;

namespace BugTracker.Controllers
{
    public class ContactController : Controller
    {
        [Route("[controller]/[action]")]
        public IActionResult Index()
        {
            return View();
        }


    }
}

BugTracker/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BugTracker.Data;
using System.Security.Claims;
using BugTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;

namespace BugTracker.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    [Route("[controller]/[action]")]
    public class TicketController : Controller
    {
        // Dependency injection
        // Inject database contents into the controller
        private readonly BugTrackerContext _context;


        public TicketController(BugTrackerContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.userId = currentUserID;

            return View(await _context.Tickets.ToListAsync());
        }

        public async Task<IActionResult> Ticket(string ? id)
        {
            // Find the correct ticket
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.TicketId == id);

            if (ticket == null)
            {
                return NotFound();
            }


            /* COLORS
            "#d4edda"
            "#fff3cd"
            "#f8d7da"
            "#cce5ff"
            */
            // Set color based on the ticket's priority
            String alertColor;
            switch ((int)ticket.TicketPriority)
            {
                case 0:
                    alertColor = "alert-success";
                    ViewBag.background = "#d4edda";
                    ViewBag.backgroundLight = "#dbf0e0";
                    break;
                case 1:
                    alertColor = "alert-warning";
                    ViewBag.background = "#fff3cd";
                    ViewBag.backgroundLight = "#fff9e6";
                    break;
                case 2:
                    alertColor = "alert-danger";
                    ViewBag.background = "#f8d7da";
                    ViewBag.backgroundLight = "#fbe9eb";
                    break;
                case 3:
                    alertColor = "alert-primary";
                    ViewBag.background = "#cce5ff";
                    ViewBag.backgroundLight = "#e6f2ff";
                    break;
                default:
                    alertColor = "alert-secondary";
                    ViewBag.background = "#d4edda";
                    ViewBag.backgroundLight = "#dbf0e0";
                    break;
            }

            ViewBag.alertColor = alertColor;

            // Display card with project associated with the ticket
            var project = await _context.Projects.FindAsync(ticket.ProjectId);

            if (project == null)
            {
                return NotFound();
            }

            ViewBag.projectName = project.ProjectName;

            LanguageImages c1 = new LanguageImages();

            // TEMPORARY SOLUTION. CONVERT LATER
            switch (project.projectLanguage)
            {
                case "C":
                    ViewBag.ProjectImage = c1.getC();
                    break;
                case "CSharp":
                    ViewBag.ProjectImage = c1.getCsharp();
                    break;
                case "Go":
                    ViewBag.ProjectImage = c1.getGo();
                    break;
                case "Java":
                    ViewBag.ProjectImage = c1.getJava();
                    break;
                case "JavaScipt":
                    ViewBag.ProjectImage = c1.getJavaScript();
                    break;
                case "PHP":
                    ViewBag.ProjectImage = c1.getPHP();
                    break;
                case "Python":
                    ViewBag.ProjectImage = c1.getPython();
                    break;
                case "Ruby":
                    ViewBag.ProjectImage = c1.getRuby();
                    break;
                case "SQL":
                    ViewBag.ProjectImage = c1.getSQL();
                    break;
                case "Swift":
                    ViewBag.ProjectImage = c1.getSwift();
                    break;
                case "TypeScript":
                    ViewBag.ProjectImage = c1.getTypeScript();
                    break;
                default:
                    break;
            }


            return View(ticket);
        }

        public async Task<IActionResult> Project(string? id)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.userId = currentUserID;


            // Pass in the project we wish to associate with the Ticket
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FirstOrDefaultAsync(m => m.projectId == id);
            if (project == null)
            {
                return NotFound();
            }

            ViewBag.ProjectId = project.projectId;


            return View(await _context.Tickets.ToListAsync());
        }

        public async Task<IActionResult> Create(string? id)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.userId = currentUserID;
            ViewBag.projectId = id;
            ViewBag.creationDate = DateTime.Now;

            // For Priority?
            //   ViewBag.PriorityList = new SelectList(Enum.GetValues(typeof(Priority)), "TicketPriority", "Description", 0);


            // @Html.DropDownList("TicketPriority",
            //             new SelectList(Enum.GetValues(typeof(Priority))),
            //            "Select Priority",
            //            new { @class = "form-control" })


            // Pass in the project we wish to associate with the Ticket
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FirstOrDefaultAsync(m => m.projectId == id);
            ViewBag.projectName = project.ProjectName;
            ViewBag.authorName = project.Author;

            if (project == null)
            {
                return NotFound();
            }

            ViewBag.Project = project;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string? id, [Bind("TicketId, TicketName, TicketDesc, userId, ProjectId, TicketPriority, projectName, authorName")] Tickets Ticket)
        {
            // 0:dd/MMM/yyyy HH:mm:ss
            // Get Current DateTime
            ViewBag.creationDate = DateTime.Now; //.ToString("0:dd/MMM/yyyy HH:mm:ss");


            ViewBag.userId = Ticket.userId;
            ViewBag.projectId = Ticket.ProjectId;

            Ticket.CreationDate = DateTime.Now; //DateTime.Now.ToString("0:dd/MMM/yyyy HH:mm:ss");
            // Add the ticket to the project's 

            if (Ticket.ProjectId == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FirstOrDefaultAsync(m => m.projectId == Ticket.ProjectId);
            if (project != null)
            {
                project.TicketList.Add(Ticket);
            }

            if (project == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                // Load the UserProjects
                var loadedUserProjects = await _context.UserProjects
                                    .Where(p => p.projectId == Ticket.ProjectId)
                                    .ToListAsync();

                BugTracker.Areas.Identity.Data.BugTrackerUser user = await _context.Users.FindAsync(Ticket.userId);

                // Create notification for everyone whose included on project
                foreach (var item in loadedUserProjects)
                {
                    if (item.Id != Ticket.userId)
                    {
                        UserNotification editNotification = new UserNotification
                        {
                            AuthorId = Ticket.userId,
                            NotificationAuthor = user,
                            AffectedId = item.Id,
                            AffectedUser = item.BugTrackerUser,
                            NotificationMessage = $"A new bug has been created in {Ticket.projectName}",
                            NotificationSeen = false,
                            Bug = true
                        };

                        _context.UserNotifications.Add(editNotification);
                    }
                }


                _context.Tickets.Add(Ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction("Project", new { id = Ticket.ProjectId });
            }

            return View(Ticket);
        }

        /*
        public async Task<IActionResult> Complete(int ? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.TicketId == id);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Complete(string id)
        {
            var Ticket = await _context.Tickets.FindAsync(id);
            if (Ticket == null)
            {
                return NotFound();

BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/DataTables.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BugTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index"> Projects </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index"> Tickets </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index"> Contact Me </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BugTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>